spring:
  application:
    name: HomeTechManagement

  # PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://ep-late-shape-ahcz0zed-pooler.c-3.us-east-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_6D5MgcNqwCvl&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_6D5MgcNqwCvl
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 60000
      idle-timeout: 300000
      max-lifetime: 1800000
      leak-detection-threshold: 10000

  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: validate # Chỉ thay đổi dữ liệu, không thay đổi cấu trúc bảng
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false

  mail:
    host: smtp.gmail.com           # Thay bằng host của dịch vụ email
    port: 587
    username: bluemoonnoreply@gmail.com # Thay bằng email gửi
    password: ahylnpruyfjuddjh                        #bluemoon20242
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Logging Configuration (merged with debug levels)
logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    com.zaxxer.hikari: DEBUG
    io.github.ktpm.bluemoonmanagement: DEBUG
